name: tes
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PASSWORD=fake_password
      - FLAG=ictf{fake_flag}
      - URL=http://localhost:8000
    restart:
      unless-stopped
